sudo: required
language: c++
services:
- docker

before_install:
  - docker pull trusch/susi-builder:stable
  - docker pull trusch/susi-arm-builder:stable

script:
  - docker run -v $(pwd):/src trusch/susi-builder:stable
  - cp build/*.deb ./susi-leveldb-${TRAVIS_BRANCH}-linux-amd64.deb
  - docker run -v $(pwd):/opt/rootfs/src trusch/susi-arm-builder:stable
  - cp build/*.deb ./susi-leveldb-${TRAVIS_BRANCH}-linux-armhf.deb

deploy:
  provider: releases
  file:
    - "susi-leveldb-${TRAVIS_BRANCH}-linux-amd64.deb"
    - "susi-leveldb-${TRAVIS_BRANCH}-linux-armhf.deb"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: OKPDpo4Gi+SLH/shSk7iv76i33lp4Z2rIwUBehMqzxzEJHk7WcI19jpTroI1dOdpSP6XaIYbdv64lH+g8KKGAiN5xKVhQJyl2kB1bKMUX1Uca5UYtIcUhTrX+a/nO+5PdInQW43ehE9OZnkWm8aTMak5lUkcpZ5XH7izophELuV7ggbuHDfTTTEhv2G9kKgLmQfbzLsJ+SGL7wurHxl2uRZky+YdcLpe+OigxPYjSL+pAVz7T8HRbObKBotcCvzfsEgM3t2gKLty22jCE16dsPCUcCI8YgIwyxPBZt8FJyA7VmsKkdSEExpL8LlS/I0/xm4iubWz23UcjGcvjbNcRujv/rx3VwXzPhqn1mLmGg67RgKMcktmhtb2A4xOiFV9UCtyPI4HaCupThwkCv8U0sk4QVvP0zHLxTFdEgSqxjoQtDKXnec12udnDEcDCE05X1cPBC9vPsJQNX/YtIdc6FeadvmK+cL0RyK+OKSMntxfUD5q/OP/71SgrW3hyJ8haFlsbhjXwq57SpApMxBvrCjDMOv9xPqFrPpmxj/GueF3XLLDzyfCFjIfD0gTmG/PhmEZTHIN3rdSPYHYoQTVTP/aqT8mkvlweJ8XhatyM7XOcYfM/rOEVzQdrrLGtmlFTex9ZJxBAPSySSG7s593fjkY7KPeMnp5NOqfsrexcY8=
